name = "AgentREPL"
uuid = "c6b0b931-bd15-49f6-a31f-cf7d80eb5e81"
version = "0.3.0"
authors = ["Samuel Talkington <talkington@pm.me>"]

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
JuliaSyntaxHighlighting = "ac6e5ff7-fb65-4e79-a425-ec3bc9c03011"
ModelContextProtocol = "c58f755f-f2a7-4f48-bf29-4e9659b78499"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Distributed = "1"
JuliaSyntaxHighlighting = "1.11, 1.12"
ModelContextProtocol = "0.4"
Pkg = "1"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
